errno=0	succeeded
